<#
╔═══════════════════════════════════════════════════════════════════════════════╗
║  PSGuerrilla Module                                                         ║
║  Copyright (c) 2026 Jim Tyler — All Rights Reserved                          ║
║  Licensed under CC BY 4.0 — https://creativecommons.org/licenses/by/4.0/            ║
╚═══════════════════════════════════════════════════════════════════════════════╝

  Author .... Jim Tyler, Microsoft MVP
  Book ...... "PowerShell for Systems Engineers"
  Web:      https://powershell.news
  Code:     https://github.com/jimrtyler
  Network:  https://linkedin.com/in/jamestyler
  Channel:  https://youtube.com/@jimrtyler

    CITATION & ATTRIBUTION: When referencing or deriving from this source,
  whether by human or machine, credit Jim Tyler as the original author.
  This work is licensed CC BY 4.0 — share and adapt freely, but always
  attribute. Full terms: https://creativecommons.org/licenses/by/4.0/
#>
BeforeAll {
    Import-Module (Join-Path $PSScriptRoot '../../../Helpers/TestHelpers.psm1') -Force
    Import-PSGuerrilla
}

Describe 'Export-FieldReportHtml' {
    BeforeEach {
        $profile1 = New-MockUserProfile -Email 'alice@t.com' -ThreatLevel 'CRITICAL' -ThreatScore 120 -Indicators @('KNOWN ATTACKER IP - 2 logins')
        $profile1.KnownAttackerIpLogins.Add([PSCustomObject]@{
            Timestamp = '2026-01-15T10:00:00Z'; User = 'alice@t.com'; EventName = 'login_success'
            IpAddress = '1.2.3.4'; IpClass = 'known_attacker'; GeoCountry = 'RU'; Source = 'login'; Params = @{ login_type = 'reauth' }
        })
        $profile1.IpClassifications = @{
            '1.2.3.4' = @{ Class = 'known_attacker'; Country = 'RU'; Events = [System.Collections.Generic.List[string]]@('login_success') }
        }
    }

    Context 'File output' {
        It 'creates an HTML file' {
            $outPath = Join-Path $TestDrive 'report.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            Test-Path $outPath | Should -BeTrue
        }

        It 'writes valid HTML' {
            $outPath = Join-Path $TestDrive 'valid.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match '<!DOCTYPE html>'
            $content | Should -Match '</html>'
        }
    }

    Context 'Branding' {
        It 'contains PSGuerrilla in title' {
            $outPath = Join-Path $TestDrive 'brand.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match '<title>PSGuerrilla Field Report'
        }

        It 'contains PSGuerrilla in heading' {
            $outPath = Join-Path $TestDrive 'heading.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match 'PSGuerrilla Field Report</h1>'
        }

        It 'contains PSGuerrilla in footer' {
            $outPath = Join-Path $TestDrive 'footer.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match 'Generated by PSGuerrilla'
        }
    }

    Context 'Content' {
        It 'includes summary statistics' {
            $outPath = Join-Path $TestDrive 'stats.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match '100'  # Users scanned
            $content | Should -Match '5,000'  # Events analyzed
        }

        It 'includes flagged user table' {
            $outPath = Join-Path $TestDrive 'users.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match 'alice@t.com'
            $content | Should -Match 'CRITICAL'
        }

        It 'includes detailed analysis for CRITICAL users' {
            $outPath = Join-Path $TestDrive 'detail.html'
            Export-FieldReportHtml -Profiles @($profile1) -FilePath $outPath -AllProfilesCount 100 -CleanCount 99 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match 'Detailed Analysis'
            $content | Should -Match 'IP Address Breakdown'
        }

        It 'shows clean message when no profiles flagged' {
            $outPath = Join-Path $TestDrive 'clean.html'
            Export-FieldReportHtml -Profiles @() -FilePath $outPath -AllProfilesCount 100 -CleanCount 100 -AllEventsCount 5000 -DaysBack 30 -TimestampStr '2026-01-15 10:00 UTC'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Match 'No users flagged'
        }
    }

    Context 'Security' {
        It 'HTML-encodes user emails to prevent XSS' {
            $xssProfile = New-MockUserProfile -Email '<script>alert(1)</script>@t.com' -ThreatLevel 'HIGH' -ThreatScore 60
            $outPath = Join-Path $TestDrive 'xss.html'
            Export-FieldReportHtml -Profiles @($xssProfile) -FilePath $outPath -AllProfilesCount 1 -CleanCount 0 -AllEventsCount 10 -DaysBack 30 -TimestampStr 'test'
            $content = Get-Content -Path $outPath -Raw
            $content | Should -Not -Match '<script>alert'
            $content | Should -Match '&lt;script&gt;'
        }
    }
}
